services:
  django:
    build: 
      context: .
      dockerfile: django_app/Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgresDB:
        condition: service_healthy
    networks:
      - app_network

  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - app_network
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: