images:
  repository: 506421742864.dkr.ecr.eu-central-1.amazonaws.com/lesson-9-chart
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_HOST: 
  POSTGRES_PORT: 5432
  POSTGRES_DB: django_db
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: 

postgresql:
  enabled: false