images:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_HOST: ""
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ""
  POSTGRES_DB: ""

secrets:
  POSTGRES_PASSWORD: ""
